apiVersion: v1
kind: Service
metadata:
  name: calculator
  namespace: app
  labels:
    app: calculator
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: calculator
